using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

public class Enemy : MonoBehaviour
{
    [SerializeField] protected string EnemyName; // ì˜ ´ë¦„
    [SerializeField] protected int hp; // ì˜ ì²´ë ¥.

    [SerializeField] protected float walkSpeed; // ê±·ê¸° ¤í”¼
    [SerializeField] protected float runSpeed; // °ê¸° ¤í”¼
    
    protected Vector3 destination; // ëª©ì ì§€.

    // íƒœë³€
    protected bool isAction; // ‰ë™ì¤‘ì¸ì§€ „ë‹Œì§€ ë³„.
    protected bool isWalking; // ê±·ëŠ”ì§€ ê±·ëŠ”ì§€ ë³„.
    protected bool isRunning; // °ëŠ”ì§€ ë³„.
    protected bool isChasing; // ì¶”ê²©ì¤‘ì¸ì§€ ë³„.

    [SerializeField] protected float walkTime; // ê±·ê¸° œê°„
    [SerializeField] protected float waitTime; // €ê¸œê°„.
    [SerializeField] protected float runTime; // °ê¸° œê°„.
    protected float currentTime;


    // „ìš”ì»´í¬ŒíŠ¸
    // [SerializeField] protected Animator anim;
    [SerializeField] protected Rigidbody rigid;
    [SerializeField] protected BoxCollider boxCol;
    protected NavMeshAgent nav;
    protected FieldOfViewAngle theViewAngle;

    [SerializeField]
    protected float ChaseTime; // ì´ì¶”ê²© œê°„
    protected float CurrentChaseTime; // ê³„ì‚°
    [SerializeField]
    protected float ChaseDelayTime; // ì¶”ê²© œë ˆ

    // Use this for initialization
    void Start()
    {
        theViewAngle = GetComponent<FieldOfViewAngle>();
        nav = GetComponent<NavMeshAgent>();
        currentTime = waitTime;
        isAction = true;
    }

    // Update is called once per frame
    protected virtual void Update()
    {        
            Move(); 
            ElapseTime();       
    }


    protected void Move()
    {
        if (isWalking || isRunning)
           nav.SetDestination(transform.position + destination * 5f);
    }


    protected void ElapseTime()
    {
        if (isAction)
        {
            currentTime -= Time.deltaTime;
            if (currentTime <= 0 && !isChasing)
                ReSet();
        }
    }

    protected virtual void ReSet()
    {
        isWalking = false; isRunning = false; isAction = true;
        nav.speed = walkSpeed;
        nav.ResetPath();
        // anim.SetBool("Walking", isWalking); anim.SetBool("Running", isRunning);
        destination.Set(Random.Range(-1f, 1f), 0f, Random.Range(-1f, 1f));
    }

    protected void TryWalk()
    {
        isWalking = true;
        // anim.SetBool("Walking", isWalking);
        currentTime = walkTime;
        nav.speed = walkSpeed;
        Debug.Log("ê±·ê¸°");
    }

    public void Run(Vector3 _targetPos)
    {
        destination = new Vector3(transform.position.x - _targetPos.x,1f, transform.position.z - _targetPos.z).normalized;
        currentTime = runTime;
        isWalking = false;
        isRunning = true;
        nav.speed = runSpeed;
        // anim.SetBool("Running", isRunning);
    }

    public void Chase(Vector3 _targetPos)
    {
        isChasing = true;
        destination = _targetPos;
        nav.speed = runSpeed;
        // anim.SetBool("Running", isRunning);
        nav.SetDestination(destination);
    }

}
